controller_list:
  - name: fake_tx90_controller
    joints:
      - tx90_joint_1
      - tx90_joint_2
      - tx90_joint_3
      - tx90_joint_4
      - tx90_joint_5
      - tx90_joint_6
  - name: fake_ur3_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
  - name: fake_irb120_controller
    joints:
      - irb120_joint_1
      - irb120_joint_2
      - irb120_joint_3
      - irb120_joint_4
      - irb120_joint_5
      - irb120_joint_6
  - name: fake_all_sub_controller
    joints:
      - ur3_shoulder_pan_joint
      - ur3_shoulder_lift_joint
      - ur3_elbow_joint
      - ur3_wrist_1_joint
      - ur3_wrist_2_joint
      - ur3_wrist_3_joint
      - irb120_joint_1
      - irb120_joint_2
      - irb120_joint_3
      - irb120_joint_4
      - irb120_joint_5
      - irb120_joint_6
      - tx90_joint_1
      - tx90_joint_2
      - tx90_joint_3
      - tx90_joint_4
      - tx90_joint_5
      - tx90_joint_6