controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [irb120_joint_1, irb120_joint_2, irb120_joint_3, irb120_joint_4, irb120_joint_5, irb120_joint_6]
