controller_list:
  - name: fake_manipulator_controller
    joints:
      - irb120_joint_1
      - irb120_joint_2
      - irb120_joint_3
      - irb120_joint_4
      - irb120_joint_5
      - irb120_joint_6