controller_list:
  - name: fake_arm_controller
    joints:
      - tx260l_joint_1
      - tx260l_joint_2
      - tx260l_joint_3
      - tx260l_joint_4
      - tx260l_joint_5
      - tx260l_joint_6
  - name: fake_gripper_eef_controller
    joints:
      - tx260l_joint_1
      - tx260l_joint_2
      - tx260l_joint_3
      - tx260l_joint_4
      - tx260l_joint_5
      - tx260l_joint_6